server:
  port: 2228

spring:
  application:
    name: cloud-turbine

management:
  server:
    port: 2230

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka/

turbine:
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    cluster-config: default
  # 指定了需要收集监控信息的服务名，多个使用","分割
  app-config: cloud-ribbon-consumer
  # 指定集群名称。以便在不同的聚合集群中做标识
  cluster-name-expression: new String('default')
  # 让同一主机上的服务通过主机名与端口号的组合来进行拆分
  combine-host-port: true
