server:
  port: 7002

spring:
  application:
    name: cloud-config-client
  # RabbitMQ 配置 Spring Cloud Bus
  #rabbitmq:
  #  host: 127.0.0.1
  #  port: 5672
  #  username: admin
  #  password: 123456

management:
  endpoints:
    web:
      exposure:
        # 开启指定端点
        # 配置刷新地址：POST http://127.0.0.1:7002/actuator/refresh
        include: refresh


