server:
  port: 7001

spring:
  application:
    name: cloud-config-server
 # RabbitMQ 配置 Spring Cloud Bus
 #rabbitmq:
 #  host: 127.0.0.1
 #  port: 5672
 #  username: admin
 #  password: 123456
  # 配置完成后可访问的 url 如下，比如：http://localhost:7001/env/default
  # /{application}/{profile} [/{label}]
  # /{application}-{profile}.yml
  # /{label}/{application}-{profile}.yml
  # /{application}-{profile}.properties
  # /{label}/{application}-{profile}.properties
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/JMCuixy/cloud-config-server.git
          # 搜索路径
          search-paths: config-repo
        # 为配置中心提供安全保护
        username: user
        password: password
        # 访问 http://localhost:7001/actuator/health 可以获取配置中心健康指标
        health:
          repositories:
            env:
              name: env
              profiles: default
              label: master
            env-dev:
              name: env-dev
              profiles: dev
              label: master
            env-test:
              name: env-test
              profiles: test
              label: master
            env-prod:
              name: env-prod
              profiles: prod
              label: master
    # 配置消息总线自动刷新配置
    bus:
      enabled: true
      # 开启跟踪总线事件
      trace:
        enabled: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        # 执行 http://127.0.0.1:7001/actuator/bus-refresh，把配置内容修改的消息发布到服务总线。
        # 客户端收到订阅消息，自动执行 /actuator/refresh，刷新配置
        include: bus-refresh


eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka/


